import { LandDocument } from '../../types/document';

export const mockDocuments: LandDocument[] = [
  {
    id: 'DOC-1001',
    title: 'Saat Bara (7/12) Extract #142/A',
    documentType: '7_12_extract',
    documentNumber: '7/12-MH-PUN-2024-142A',
    state: 'Maharashtra',
    district: 'Pune',
    taluka: 'Haveli',
    village: 'Hadapsar',
    surveyNumber: '142/A',
    fileUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=800',
    fileSize: '2.4 MB',
    uploadedBy: 'Rajesh Sharma',
    uploadedAt: '2026-08-28 10:15',
    status: 'verified',
    ocrAccuracy: 98.5,
    extractedFields: [
      { key: 'owner_name', label: 'Primary Owner Name', value: 'Rameshwar Mahadev Patil', confidence: 99.2 },
      { key: 'survey_no', label: 'Survey / Gut Number', value: '142/A', confidence: 99.8 },
      { key: 'total_area', label: 'Total Area (Hectares)', value: 1.45, confidence: 98.9 },
      { key: 'land_use', label: 'Land Use Type', value: 'Jirayat Agricultural', confidence: 97.4 },
      { key: 'encumbrances', label: 'Bank Mortgage/Encumbrance', value: 'SBI Agricultural Loan Rs. 4,50,000', confidence: 95.1 },
    ],
  },
  {
    id: 'DOC-1002',
    title: 'Mutation Ferfar Register #88',
    documentType: 'mutation_register',
    documentNumber: 'MUT-MH-PUN-2024-088',
    state: 'Maharashtra',
    district: 'Pune',
    taluka: 'Haveli',
    village: 'Mavli',
    surveyNumber: '143/B',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=800',
    fileSize: '1.8 MB',
    uploadedBy: 'Suresh Deshmukh',
    uploadedAt: '2026-08-28 11:30',
    status: 'discrepancy',
    ocrAccuracy: 84.2,
    discrepancies: [
      'Name spelling mismatch between Mutation Register & Sale Deed',
      'Boundary overlap of 0.05 Ha detected with adjacent plot #144',
    ],
    extractedFields: [
      { key: 'owner_name', label: 'Seller Name', value: 'Suresh Vishnu Deshmukh', confidence: 88.0, isFlagged: true },
      { key: 'buyer_name', label: 'Buyer Name', value: 'Vikram Pratap Rao', confidence: 85.5 },
      { key: 'survey_no', label: 'Survey / Gut Number', value: '143/B', confidence: 96.0 },
      { key: 'transfer_area', label: 'Transferred Area', value: 0.92, confidence: 91.2 },
    ],
  },
  {
    id: 'DOC-1003',
    title: 'Khatauni Ownership Record #410',
    documentType: 'khatauni',
    documentNumber: 'KHT-UP-LKN-2024-410',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    taluka: 'Sarojini Nagar',
    village: 'Bani',
    surveyNumber: '410/1',
    fileUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=800',
    fileSize: '3.1 MB',
    uploadedBy: 'Anil Verma',
    uploadedAt: '2026-08-27 14:20',
    status: 'digitized',
    ocrAccuracy: 97.1,
    extractedFields: [
      { key: 'khata_no', label: 'Khatauni Khata Number', value: '410/1', confidence: 98.4 },
      { key: 'khasra_no', label: 'Khasra Plot Numbers', value: '88/1, 88/2, 89', confidence: 97.8 },
      { key: 'total_area', label: 'Total Area (Hectares)', value: 2.10, confidence: 96.9 },
    ],
  },
];
