import os
from pathlib import Path
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.barcode import qr
from ..config import UPLOAD_DIR

def generate_approval_pdf(
    approval_ref: str,
    submission_ref: str,
    citizen_name: str,
    survey_number: str,
    owner_name: str,
    area: str,
    village: str,
    taluk: str,
    district: str,
    document_number: str,
    document_date: str,
    officer_name: str,
    officer_code: str,
    officer_designation: str,
    approval_date: datetime,
    remarks: str,
    verification_summary: str = "Discrepancy resolved through officer manual verification",
) -> str:
    """
    Generates an official-looking prototype approval PDF using ReportLab.
    Returns the absolute file path of the generated PDF.
    """
    filename = f"Approval_{approval_ref.replace('/', '_')}.pdf"
    pdf_path = UPLOAD_DIR / filename

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        alignment=1,  # Center
        textColor=colors.HexColor('#0f172a'),
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=15,
        alignment=1,
        textColor=colors.HexColor('#0284c7'),
    )
    warning_style = ParagraphStyle(
        'WarningBanner',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        alignment=1,
        textColor=colors.HexColor('#b91c1c'),
    )
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=6,
    )
    body_text = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#334155'),
    )
    bold_text = ParagraphStyle(
        'BodyDarkBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#0f172a'),
    )

    story = []

    # 1. Header & Title
    story.append(Paragraph("BHOOMIX", title_style))
    story.append(Paragraph("AI-POWERED HISTORICAL LAND RECORD DIGITIZATION & REVENUE VERIFICATION SYSTEM", subtitle_style))
    story.append(Paragraph("PROTOTYPE LAND RECORD DIGITIZATION AND VERIFICATION APPROVAL FORM", ParagraphStyle(
        'HeaderForm',
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        alignment=1,
        textColor=colors.HexColor('#047857'),
    )))
    story.append(Spacer(1, 10))

    # Prominent Prototype Disclaimer Box
    disclaimer_html = (
        "<b>PROTOTYPE VERIFICATION RECORD – NOT A GOVERNMENT CERTIFICATE</b><br/>"
        "THIS IS A DEMONSTRATION PROTOTYPE RECORD GENERATED BY BHOOMIX. "
        "IT DOES NOT CONSTITUTE A LEGALLY BINDING TITLE DEED OR STATUTORY GOVERNMENT CERTIFICATE."
    )
    disclaimer_table = Table(
        [[Paragraph(disclaimer_html, warning_style)]],
        colWidths=[530],
    )
    disclaimer_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fee2e2')),
        ('BORDER', (0, 0), (-1, -1), 1, colors.HexColor('#ef4444')),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    story.append(disclaimer_table)
    story.append(Spacer(1, 12))

    # 2. Key References Table
    ref_data = [
        [
            Paragraph("<b>Approval Reference:</b>", bold_text),
            Paragraph(approval_ref, bold_text),
            Paragraph("<b>Submission Reference:</b>", bold_text),
            Paragraph(submission_ref, bold_text),
        ],
        [
            Paragraph("<b>Approval Date:</b>", body_text),
            Paragraph(approval_date.strftime("%d-%b-%Y %H:%M UTC"), body_text),
            Paragraph("<b>Citizen Name:</b>", body_text),
            Paragraph(citizen_name, body_text),
        ]
    ]
    ref_table = Table(ref_data, colWidths=[130, 135, 130, 135])
    ref_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(ref_table)
    story.append(Spacer(1, 14))

    # 3. Verified Land Record Details
    story.append(Paragraph("1. VERIFIED LAND RECORD PARTICULARS", section_heading))
    land_data = [
        [Paragraph("<b>Survey / Gut Number:</b>", bold_text), Paragraph(survey_number, bold_text),
         Paragraph("<b>Registered Owner:</b>", bold_text), Paragraph(owner_name, bold_text)],
        [Paragraph("<b>Land Area / Extent:</b>", body_text), Paragraph(area, body_text),
         Paragraph("<b>Document Number:</b>", body_text), Paragraph(document_number or "N/A", body_text)],
        [Paragraph("<b>Village:</b>", body_text), Paragraph(village, body_text),
         Paragraph("<b>Document Date:</b>", body_text), Paragraph(document_date or "N/A", body_text)],
        [Paragraph("<b>Taluk:</b>", body_text), Paragraph(taluk, body_text),
         Paragraph("<b>District:</b>", body_text), Paragraph(district, body_text)],
    ]
    land_table = Table(land_data, colWidths=[130, 135, 130, 135])
    land_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(land_table)
    story.append(Spacer(1, 14))

    # 4. Verification Summary
    story.append(Paragraph("2. SYSTEM VERIFICATION & AUDIT SUMMARY", section_heading))
    verif_data = [
        [Paragraph("<b>OCR Extraction Pipeline:</b>", body_text), Paragraph("Completed (Multi-layer character recognition)", bold_text)],
        [Paragraph("<b>Reference Record Cross-Check:</b>", body_text), Paragraph("Completed against secure Reference Database", bold_text)],
        [Paragraph("<b>Discrepancy Status:</b>", body_text), Paragraph(verification_summary, bold_text)],
        [Paragraph("<b>Revenue Officer Review:</b>", body_text), Paragraph("Completed & Formally Approved", bold_text)],
        [Paragraph("<b>Final Verification Status:</b>", bold_text), Paragraph("<font color='#047857'><b>APPROVED</b></font>", bold_text)],
    ]
    verif_table = Table(verif_data, colWidths=[200, 330])
    verif_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f8fafc')),
    ]))
    story.append(verif_table)
    story.append(Spacer(1, 14))

    # 5. Revenue Officer Sign-Off & QR Code
    story.append(Paragraph("3. REVENUE OFFICER ENDORSEMENT & AUTHENTICATION", section_heading))

    # QR Code containing non-sensitive verification reference URL
    qr_url = f"http://localhost:3000/verify/{approval_ref}"
    qr_draw = Drawing(75, 75)
    qr_widget = qr.QrCodeWidget(qr_url)
    qr_widget.barWidth = 70
    qr_widget.barHeight = 70
    qr_draw.add(qr_widget)

    officer_sign_content = (
        f"<b>Officer Name:</b> {officer_name}<br/>"
        f"<b>Officer Code:</b> {officer_code}<br/>"
        f"<b>Designation:</b> {officer_designation}<br/>"
        f"<b>Officer Remarks:</b> {remarks or 'Verified against physical scanned documentation.'}<br/>"
        f"<b>Digital Timestamp:</b> {approval_date.strftime('%Y-%m-%d %H:%M:%S UTC')}"
    )

    qr_desc = (
        "<b>Verification QR:</b><br/>"
        "<font size='7' color='#64748b'>Scan with any QR reader to verify prototype reference authenticity. Contains non-sensitive reference URL.</font>"
    )

    officer_data = [
        [
            Paragraph(officer_sign_content, body_text),
            [qr_draw, Paragraph(qr_desc, body_text)],
        ]
    ]
    officer_table = Table(officer_data, colWidths=[380, 150])
    officer_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(officer_table)

    # Footer Watermark Notice
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>Generated by BhoomiX Prototype Engine. Demo data only – not connected to live government land records.</i>",
        ParagraphStyle('FooterText', fontName='Helvetica-Oblique', fontSize=7.5, leading=10, alignment=1, textColor=colors.HexColor('#94a3b8'))
    ))

    doc.build(story)
    return str(pdf_path)
