import { LandDocument } from '../../types/document';

export const mockDocuments: LandDocument[] = [
  {
    id: 'DOC-3463',
    title: 'Patta / Chitta Extract Deed #132/1',
    documentType: '7_12_extract',
    documentNumber: 'TN-DHM-PPR-2003-3463',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    taluka: 'Pappireddipatti',
    village: 'Payanatham',
    surveyNumber: '132/1',
    fileUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=800',
    fileSize: '2.4 MB',
    uploadedBy: 'R. Ananthi',
    uploadedAt: '2026-09-18 10:15',
    status: 'verified',
    ocrAccuracy: 94.2,
    extractedFields: [
      { key: 'owner_name', label: 'Primary Owner Name', value: 'R. Ananthi', confidence: 96.0 },
      { key: 'survey_no', label: 'Survey / Subdivision Number', value: '132/1', confidence: 97.5 },
      { key: 'total_area', label: 'Total Land Extent', value: 1.20, confidence: 91.0 },
      { key: 'land_use', label: 'Land Classification', value: 'Ryotwari Punja', confidence: 95.0 },
      { key: 'encumbrances', label: 'Sub-Registrar Jurisdiction', value: 'Pappireddipatti SRO • Clear Title', confidence: 94.0 },
    ],
  },
  {
    id: 'DOC-1088',
    title: 'Adangal Land Cultivation Register #45/2',
    documentType: 'mutation_register',
    documentNumber: 'TN-SLM-ATT-2021-1088',
    state: 'Tamil Nadu',
    district: 'Salem',
    taluka: 'Attur',
    village: 'Valapadi',
    surveyNumber: '45/2',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=800',
    fileSize: '1.8 MB',
    uploadedBy: 'S. Murugan',
    uploadedAt: '2026-09-19 11:30',
    status: 'discrepancy',
    ocrAccuracy: 88.2,
    discrepancies: [
      'Subdivision number requires verification against FMB sketch',
      'Extent notation format reconciliation required',
    ],
    extractedFields: [
      { key: 'owner_name', label: 'Registered Pattadar', value: 'S. Murugan', confidence: 89.0, isFlagged: true },
      { key: 'survey_no', label: 'Survey / Gut Number', value: '45/2', confidence: 96.0 },
      { key: 'transfer_area', label: 'Recorded Extent', value: 0.85, confidence: 91.2 },
    ],
  },
  {
    id: 'DOC-2204',
    title: 'Registered Historical Sale Deed #88/3',
    documentType: 'khatauni',
    documentNumber: 'TN-KRI-HOS-2018-2204',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    taluka: 'Hosur',
    village: 'Bagalur',
    surveyNumber: '88/3',
    fileUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=800',
    fileSize: '3.1 MB',
    uploadedBy: 'K. Selvam',
    uploadedAt: '2026-09-19 14:20',
    status: 'digitized',
    ocrAccuracy: 96.4,
    extractedFields: [
      { key: 'owner_name', label: 'Pattadar Name', value: 'K. Selvam', confidence: 98.4 },
      { key: 'survey_no', label: 'Survey Number', value: '88/3', confidence: 97.8 },
      { key: 'total_area', label: 'Land Area (Acres)', value: 2.10, confidence: 96.9 },
    ],
  },
];
